version: '3'
services:
  consul-server:
    image: "consul"
    ports:
      - "8500:8500"
  consul-import:
    image: "consul"
    links:
      - "consul-server:consul-server"
    volumes:
      - ./consul-import/import.json:/import/import.json
    depends_on:
      - consul-server
    command: consul kv import -http-addr consul-server:8500 @/import/import.json
  nginx-consul-template:
    build: nginx-consul-template
    ports:
      - "80:80"
    links:
      - "consul-server:consul-server"
    volumes:
      - ./nginx-consul-template/default.conf.ctmpl:/etc/nginx/conf.d/default.conf.ctmpl
    environment:
      - CONSUL_HOST=consul-server:8500
      - CONSUL_LOG_LEVEL=debug
    depends_on:
      - consul-import
